In [1]:
import pandas as pd
from fuzzywuzzy import fuzz
from fuzzy_match import algorithims
import json
import nltk
from nltk.tokenize import WordPunctTokenizer
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# nltk.download('stopwords')
# nltk.download('punkt')

stop_words={'but', 'aren', 'by', 'during', "isn't", "won't", 'through', 'only', 'up', 'we', 'o', 'very', 'off', 'here', 'hasn', 
            'does', 'that', "shouldn't", 'wasn', 'of', 'shan', 'yourselves', 'my', 'd', "you'd", 'further', 'too', "that'll", 
            'these', 'or', 'before', 'each', 'm', 'all', 'at', "didn't", "doesn't", 'be', 'the', 'are', 'been', 'being', 'didn'
            , 'if', 'their', 'until', 'i', 'hadn', 'against', 'to', 'once', 'your', 'am', 'just', 'again', 'with', 'while', 
            'between', "needn't", 'a', "it's", 'where', 'themselves', 'after', 'don', 'ma', 'when', "mustn't", 'ours', 'can',
            "hasn't", 'both', 'is', 'under', 'have', 't', 'he', 'she', 'will', 'hers', 'were', 'own', "mightn't", 
            'doing', 'shouldn', 'herself', 'wouldn', 'above', 'yours', 've', "don't", 'an', 'any', 'same', 'no', 'do',
            'there', 'nor', 'some', "weren't", 'our', 'll', 'did', 'should', "aren't", 'won', 're', 'not', 'this', 'than', 
            's', 'has', 'had', "should've", 'what', "couldn't", 'then', 'haven', 'into', 'from', "shan't", 'y', 'such',
            'below', 'few', 'they', 'having', 'her', "wasn't", 'was', 'needn', 'ourselves', "you've", "wouldn't", 
            'on', 'over', 'because', 'as', "haven't", 'its', 'you', 'isn', "she's", 'those', "hadn't", 'more', 'myself',
            'him', 'which', 'it', 'weren', "you'll", 'for', 'himself', 'and', 'itself', 'now', 'doesn', 'other', 'me', 'them',
            'out', 'ain', "you're", 'most', 'could not', 'his', 'mightn', 'who', 'in', 'so', 'whom', 'yourself', 'why', 'theirs',
            'mustn', 'down',"tell","get","how"}

C:\Users\DELL\anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [2]:
%%writefile content1.json
{
  "intents": [
{
  "tag": "department",
  "pattern":[ "vision of computer department"],
  "response": "To empower young generations for significant contribution in the field of computer engineering through excellence in knowledge, technical education and innovation to cater the industrial demands and societal needs."},{
  "tag": "department",
  "pattern": ["mission of computer department"],
  "response": "To undertake collaborative training which offer opportunities for long term interaction with academia and industry."
},{
  "tag": "department",
  "pattern": ["Number of labs", "count of lab"],
  "response": "12"
},{
  "tag": "department",
  "pattern": ["Operating System Lab","OSL","os lab"],
  "response": "Operating System: Windows 7,Programming tools: Arduino IDE",
  "link": "http://www.snjb.org/engineering/Computer_engineering/computer_engineering_laboratories"
},{
  "tag": "department",
  "pattern": ["Area of Operating System Lab", "os lab(OSL)"],
  "response": "Area of Lab:. 66 Sq.m.",
  "link": "http://www.snjb.org/engineering/images/department/Operating_System_Lab.png"
},{
  "tag": "department",
  "pattern": ["Lab Incharge of operation system lab", "os lab"],
  "response":"Prof. P. N. Achaliya",
  "link": "http://www.snjb.org/engineering/images/department/Operating_System_Lab.png"
},{
  "tag": "department",
  "pattern": ["Software Laboratory","sl"],
  "response": "Programming Tools Anaconda Navigator,Python,Cisco Packet Tracer, Wireshark, Browsers: Mozilla Firefox, Google Chrome, ",
  "link": "http://www.snjb.org/engineering/Computer_engineering/computer_engineering_laboratoriess"
},{
  "tag": "department",
  "pattern":[ "Area of Software Laboratory" , "sl lab"],
  "response": "68 Sqm",
  "link": "http://www.snjb.org/engineering/images/department/LRM_EXPORT_20180820_211245imgFile5b7fbfc2b0165_thumb.jpg"
},{
  "tag": "department",
  "pattern": ["Lab Incharge SL Lab"],
  "response": "Prof. S. B. Ambhore",
  "link": "http://www.snjb.org/engineering/images/department/LRM_EXPORT_20180820_211245imgFile5b7fbfc2b0165_thumb.jpg"
},{
  "tag": "department",
  "pattern": ["Computer Networking Laboratory", "CNL"],
  "response": "Operating System Windows 7, Programming Tools: Sublime Editor, Java , Java MySQL Connector, Tomcat , XAMPP, Anaconda Navigator. Visual Studio Code, Turbo C++.",
  "link": "http://www.snjb.org/engineering/images/department/c2_thumb.jpg"
},{
  "tag": "department",
  "pattern": ["Area of Networking Laboratory" ,"CNL"],
  "response": "69 Sqm",
  "link": "http://www.snjb.org/engineering/images/department/c2_thumb.jpg"
},{
  "tag": "department",
  "pattern": ["Lab Incharge Networking lab", "CNL"],
  "response": "Prof. G. P. Dhomse",
  "link": "http://www.snjb.org/engineering/images/department/c2_thumb.jpg"
},{
  "tag": "department",
  "pattern": ["Computer Graphics Laboratory, CGL"],
  "response": ["Operating System WINDOWS 7, UBUNTU\nProgramming Tools: G++ (Graphics),Eclipse,Java,OpenGL,Turbo c,Python"],
  "link": "http://www.snjb.org/engineering/Computer_engineering/computer_engineering_laboratories"
},{
  "tag": "department",
  "pattern": ["Area of CGL" , "Area of Computer graphics lab"],
  "response": "176.5 sq. m. (Combined Project Lab + GC Lab)",
  "link": "http://www.snjb.org/engineering/images/department/Comp_Lab_CGL_thumb.jpg"
},{
  "tag": "department",
  "pattern": ["Lab In-charge of computer graphics lab, CGL"],
  "response": "Prof. N. P. Bora",
  "link": "http://www.snjb.org/engineering/images/department/Comp_Lab_CGL_thumb.jpgg"
},{
  "tag": "department",
  "pattern": ["Computer Science Laboratory"],
  "response": "Programming Tools Anaconda Navigator,Python,Cisco Packet Tracer, Wireshark",
  "link": "http://www.snjb.org/engineering/images/department/Comp_CSL_Lab_thumb.jpg"
},{
  "tag": "department",
  "pattern": ["Area of computer science Laboratory, CSL lab"],
  "response": "95.14 Sqm",
  "link": "http://www.snjb.org/engineering/images/department/Comp_CSL_Lab_thumb.jpg"
},{
  "tag": "department",
  "pattern": ["Lab In-charge computer science lab"],
  "response": "Prof. R. R. Bha,
  "link": "http://www.snjb.org/engineering/images/department/Comp_CSL_Lab_thumb.jpg"
},{
  "tag": "department",
  "pattern": ["Programming Laboratory, PL lab"],
  "response": "Programming Tools Turbo C Eclipse,starUML ,Open MP,Open , CL,Java, Gcc Lib,Lex and Yacc,NASM Python,Mongo,DB,Winedit,Miktek2.9,Winrar,Wireshark,Tasm,Qt Creator, Apache Tomcat,MysqlVLC Media Player",
    "link": "http://www.snjb.org/engineering/Computer_engineering/computer_engineering_laboratories"
},{
  "tag": "department",
  "pattern": ["Area of programing Laboratory"],
  "response": ["66 Sqm"],
  "link": "http://www.snjb.org/engineering/images/department/IMG_9770_thumb.JPG"
},{
  "tag": "department",
  "pattern": ["Lab In-charge of programming lab"],
  "response": "Prof. Pawar D. P.",
  "link": "http://www.snjb.org/engineering/images/department/IMG_9770_thumb.JPG"
},{
  "tag": "department",
  "pattern": ["Advance Programming Laboratory, APL lab"],
  "response": "Programming Tools: Turbo c, Eclipse, Java, Python,Juputer,Anaconda 3",
  "link": "http://www.snjb.org/engineering/Computer_engineering/computer_engineering_laboratories"
},{
  "tag": "department",
  "pattern": ["Area of programming Laboratory, apl lab"],
  "response": " 71.39 Sqm",
  "link": "http://www.snjb.org/engineering/images/department/apl.png"
},{
  "tag": "department",
  "pattern": ["Lab in-charge of advance programming lab, Lab in-charge of apl lab"],
  "response": " Prof. S. V. Sinha",
  "link": "http://www.snjb.org/engineering/images/department/apl.png"
},{
  "tag": "department",
  "pattern": ["result of computer deapartment"],
  "link": ["http://www.snjb.org/engineering/Computer_engineering/computer_engineering_results"]
},{
  "tag": "department",
  "pattern": ["toppers of compueter"],
    "response":"hoo",
  "link": "http://www.snjb.org/engineering/Computer_engineering/computer_engineering_placements_statistics"
},{
  "tag": "department",
  "pattern": ["placement of 2022 computer department"],
  "response": "53 placement in 2022, 279 in last 5 years",
  "link": "http://www.snjb.org/engineering/images/department/Update_Placement_Summery_Computer_Per.png"
}]
}

Overwriting content1.json

In [2]:
with open("content.json") as content:
    data1=json.load(content)

In [3]:
data1

{'intents': [{'tag': 'college name',
   'patterns': ['college name',
    'about your college',
    'name college',
    'some idea about your college'],
   'responses': ["SNJB's Late Sau. Kantabai Bhavarlalji Jain College of Engineering,Chandwad"]},
  {'tag': 'department name',
   'patterns': ['Deparment name in college',
    'stream name in college',
    'availabe courses in college',
    'how many department college',
    'count department name',
    'available department',
    'how many department are available in your college',
    'number of department',
    'count of total department',
    'total department in college'],
   'responses': ['There are total six deparments in our college including Computer , Mechanical, Civil , E & TC , AIDS , MBA etc.']},
  {'tag': 'vision and mission',
   'patterns': ['Vision of Mission college',
    'vision and mission of college',
    'goals of your college',
    'vision of college',
    'mission of college'],
   'responses': ['Vision of Our college is Transform young aspirant learners towards creativity and professionalism for societal growth through quality technical education.  and Mission is To share values, ideas, beliefs by encouraging faculties and students for welfare of society.']},
  {'tag': 'year',
   'patterns': ['established year of college',
    'when college is started',
    'year college started',
    'year when college is extablished'],
   'responses': ['2003']},
  {'tag': 'principal',
   'patterns': ['principal name of college',
    'about principal',
    'information about principal',
    'who is principal can you tell me name'],
   'responses': ["Dr.M.D.Kokate is Principal of SNJB's KBJ College of Engineering Chandwad"]},
  {'tag': 'library',
   'patterns': ['library information',
    'information about library',
    'information of library',
    'is snjb college library is good',
    'how is infrastructure of library'],
   'responses': ['We have an excellent, attractive and pleasant ambiance library in the college. Library is located at first floor & Second floor of college building, having total area of 490 sq. mtr.']},
  {'tag': 'Placement',
   'patterns': ['placement information 2021 and 2022',
    'about placement',
    'is college provide a good recruters'],
   'responses': ['in 2021 22 placement count was 38 candidates from computer department, in 2020 21 placement count was 48 cag']},
  {'tag': 'vice principal',
   'patterns': ['name of vice principal',
    'about vice principal',
    'information about vice principal'],
   'responses': ["Sanghavi Sir is vice principle of SNJB's KBJ College of Engineering Chandwad"]},
  {'tag': 'computer department lab',
   'patterns': ['how many labs in computer department',
    'Number of labs in computer department',
    'count of computer depatment lab',
    'total labs in computer department',
    'how many labs are avilable in computer department'],
   'responses': ['Total 12 Labs are available in computer department']}]}

In [4]:
tags=[]

responses={}
patt=[]
filter_sentence = []
for intent in data1['intents']:
    responses[intent['tag']]=intent['responses']
    for lines in intent['patterns']:
        patt.append(lines)
        tags.append(intent['tag'])

# # stop_words = set(stopwords.words('english'))
# filter_sentence = [w for w in ntokens if not w.lower() in stop_words]
# for ntokens in patterns:
#     word_tokens = word_tokenize(ntokens)
#     filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
#     #with no lower case conversion
#     filtered_sentence = []
#     for w in word_tokens:
#         if w not in stop_words:
#             filtered_sentence.append(w)
#             patt.append(str(" ".join([c for c in filter_sentence])))
    
# patt
# patt
len(tags)

43

In [5]:
# tags=[]
# patterns=[]
# responses=[]
# for intent in data1['intents']:
# #      responses[intent['tag']]=intent['responses']
#     for res in intent['responses']:
#         for lines in intent['patterns']:
#             patterns.append(lines)
#             responses.append(res)
#             tags.append(intent['tag'])
        
patterns=[]
for i in patt:  
    word_tokens = word_tokenize(i)
    # converts the words in word_tokens to lower case and then checks whether 
    #they are present in stop_words or not
    filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
    #with no lower case conversion
    filtered_sentence = []

    for w in word_tokens:
        if w not in stop_words:
            filtered_sentence.append(w)
    patterns.append(" ".join(filtered_sentence))
    

# patterns
tags

['college name',
 'college name',
 'college name',
 'college name',
 'department name',
 'department name',
 'department name',
 'department name',
 'department name',
 'department name',
 'department name',
 'department name',
 'department name',
 'department name',
 'vision and mission',
 'vision and mission',
 'vision and mission',
 'vision and mission',
 'vision and mission',
 'year',
 'year',
 'year',
 'year',
 'principal',
 'principal',
 'principal',
 'principal',
 'library',
 'library',
 'library',
 'library',
 'library',
 'Placement',
 'Placement',
 'Placement',
 'vice principal',
 'vice principal',
 'vice principal',
 'computer department lab',
 'computer department lab',
 'computer department lab',
 'computer department lab',
 'computer department lab']

In [6]:
data=pd.DataFrame({"inputs":patterns,
                   "tags":tags
                  })
import string 
data['inputs']=data['inputs'].apply(lambda wrd:[ltrs.lower() for ltrs in wrd if ltrs not in string.punctuation])
data['inputs']=data['inputs'].apply(lambda wrd:''.join(wrd))
data
data

                                    inputs                     tags
0                             college name             college name
1                            about college             college name
2                             name college             college name
3                       idea about college             college name
4                   deparment name college          department name
5                      stream name college          department name
6                 availabe courses college          department name
7                  many department college          department name
8                    count department name          department name
9                     available department          department name
10       many department available college          department name
11                       number department          department name
12                  count total department          department name
13                total department college          department name
14                  vision mission college       vision and mission
15                  vision mission college       vision and mission
16                           goals college       vision and mission
17                          vision college       vision and mission
18                         mission college       vision and mission
19                established year college                     year
20                         college started                     year
21                    year college started                     year
22                year college extablished                     year
23                  principal name college                principal
24                         about principal                principal
25             information about principal                principal
26                          principal name                principal
27                     library information                  library
28               information about library                  library
29                     information library                  library
30               snjb college library good                  library
31                  infrastructure library                  library
32         placement information 2021 2022                Placement
33                         about placement                Placement
34          college provide good recruters                Placement
35                     name vice principal           vice principal
36                    about vice principal           vice principal
37        information about vice principal           vice principal
38           many labs computer department  computer department lab
39         number labs computer department  computer department lab
40            count computer depatment lab  computer department lab
41          total labs computer department  computer department lab
42  many labs avilable computer department  computer department lab

In [7]:
# compares entire string similarity
def get_ratio(row,text):
    col1=row['inputs']
    col2=row['tags']
    return fuzz.ratio(col1,text)

In [8]:
# compare the partial strng similarity
def get_partial_ratio(row):
    col1=row['inputs']
    col2=row['tags']
    return fuzz.partial_ratio(col1,text)

In [9]:
# ignores word order
def get_token_sort(row):
    col1=row['inputs']
    col2=row['tags']
    return fuzz.token_sort_ratio(col1,text)

In [10]:
# ignore duplicate words similarity to token sort ratio
def get_token_set_ratio(row,text):
    col1=row['inputs']
    col2=row['tags']
    return fuzz.token_set_ratio(col1,text)

In [11]:
token_set_ratio=[]
token_ratio=[]
text="sn jb ege coll " 
ntokens = word_tokenize(text)
filter_sentence = [w for w in ntokens if not w.lower() in stop_words]
filter_sentence = []
for w in ntokens:
    if w not in stop_words:
        filter_sentence.append(w)
punc = string.punctuation
text = str(" ".join([c for c in filter_sentence if c not in string.punctuation]))
print(text)
# token_set_ratio.append(data.apply(lambda t:get_token_set_ratio(t,text),axis=1))
# token_ratio.append(data.apply(lambda t:get_ratio(t,text),axis=1))
data['set_ratio']=data.apply(lambda t:get_token_set_ratio(t,text),axis=1)
data['full_ratio']=data.apply(lambda t:get_ratio(t,text),axis=1)
data

sn jb ege coll

,inputs,tags,set_ratio,full_ratio
0,college name,college name,69,31
1,about college,college name,52,44
2,name college,college name,69,54
3,idea about college,college name,50,38
4,deparment name college,department name,50,39
5,stream name college,department name,61,48
6,availabe courses college,department name,47,42
7,many department college,department name,49,49
8,count department name,department name,17,11
9,available department,department name,29,18
10,many department available college,department name,38,38
11,number department,department name,19,26
12,count total department,department name,17,17
13,total department college,department name,47,42
14,vision mission college,vision and mission,56,44
15,vision mission college,vision and mission,56,44
16,goals college,vision and mission,67,44
17,vision college,vision and mission,71,50
18,mission college,vision and mission,69,48
19,established year college,year,47,37
20,college started,year,62,28
21,year college started,year,53,35
22,year college extablished,year,53,32
23,principal name college,principal,50,44
24,about principal,principal,21,21
25,information about principal,principal,15,24
26,principal name,principal,21,21
27,library information,library,6,6
28,information about library,library,15,26
29,information library,library,6,18
30,snjb college library good,library,62,46
31,infrastructure library,library,22,22
32,placement information 2021 2022,Placement,13,13
33,about placement,Placement,21,21
34,college provide good recruters,Placement,45,18
35,name vice principal,vice principal,18,30
36,about vice principal,vice principal,24,35
37,information about vice principal,vice principal,17,35
38,many labs computer department,computer department lab,23,28
39,number labs computer department,computer department lab,22,27
40,count computer depatment lab,computer department lab,24,24
41,total labs computer department,computer department lab,23,23
42,many labs avilable computer department,computer department lab,23,31

In [12]:
def get_trigram_ratio(row):
    col1=row['inputs']
    col2=row['tags']
    return round(algorithims.trigram(col1,text),3)
token_set_ratio=[]
token_ratio=[]
text="about principal name of college" 
ntokens = word_tokenize(text)
filter_sentence = [w for w in ntokens if not w.lower() in stop_words]
filter_sentence = []
for w in ntokens:
    if w not in stop_words:
        filter_sentence.append(w)
punc = string.punctuation
text = str(" ".join([c for c in filter_sentence if c not in string.punctuation]))
print(text)
token_set_ratio.append(data.apply(lambda t:get_token_set_ratio(t,text),axis=1))
token_ratio.append(data.apply(lambda t:get_ratio(t,text),axis=1))
data['set_ratio']=data.apply(lambda t:get_token_set_ratio(t,text),axis=1)
data['full_ratio']=data.apply(lambda t:get_ratio(t,text),axis=1)
token_set_ratio=list(token_set_ratio[0][1:])
# print(max(token_set_ratio))
token_ratio=list(token_ratio[0][1:])
tsr=max(token_set_ratio)
fr=max(token_ratio)

print(tsr,fr)
if tsr>=90 and fr>=62:
        index=token_set_ratio.index(max(token_set_ratio))
        print(index)
        value=data.iloc[index]
        print(value)
        print(responses[value['tags']])
else:
        print("Try again")
        ask()
# token_set_ratio=token_set_ratio.append(data.apply(lambda t:get_token_set_ratio(t,text),axis=1))
# token_ratio.append(data.apply(lambda t:get_ratio(t,text),axis=1))
data

about principal name college
100 88
0
inputs        college name
tags          college name
set_ratio              100
full_ratio              35
Name: 0, dtype: object
["SNJB's Late Sau. Kantabai Bhavarlalji Jain College of Engineering,Chandwad"]

,inputs,tags,set_ratio,full_ratio
0,college name,college name,100,35
1,about college,college name,100,63
2,name college,college name,100,60
3,idea about college,college name,84,57
4,deparment name college,department name,71,60
5,stream name college,department name,77,68
6,availabe courses college,department name,50,54
7,many department college,department name,47,55
8,count department name,department name,41,45
9,available department,department name,33,21
10,many department available college,department name,46,46
11,number department,department name,13,22
12,count total department,department name,28,40
13,total department college,department name,46,58
14,vision mission college,vision and mission,48,48
15,vision mission college,vision and mission,48,48
16,goals college,vision and mission,70,54
17,vision college,vision and mission,67,52
18,mission college,vision and mission,64,42
19,established year college,year,45,46
20,college started,year,64,33
21,year college started,year,52,38
22,year college extablished,year,45,35
23,principal name college,principal,100,88
24,about principal,principal,100,70
25,information about principal,principal,71,55
26,principal name,principal,100,67
27,library information,library,17,21
28,information about library,library,38,30
29,information library,library,17,17
30,snjb college library good,library,44,34
31,infrastructure library,library,16,24
32,placement information 2021 2022,Placement,20,24
33,about placement,Placement,51,51
34,college provide good recruters,Placement,48,24
35,name vice principal,vice principal,85,47
36,about vice principal,vice principal,86,62
37,information about vice principal,vice principal,70,50
38,many labs computer department,computer department lab,28,25
39,number labs computer department,computer department lab,27,24
40,count computer depatment lab,computer department lab,39,29
41,total labs computer department,computer department lab,28,34
42,many labs avilable computer department,computer department lab,33,36

In [13]:
# # data['full ratio']=data.apply(get_ratio,axis=1)
# # data['partial_ratio']=data.apply(get_partial_ratio,axis=1)
# # data['token_sort_ratio']=data.apply(get_token_sort,axis=1)
# data['token_set_ration']=data.apply(get_token_set_ratio,axis=1)
# # data['trigram']=data.apply(get_trigram_ratio,axis=1)
# full_ratio=[]
# token_set_ratio=[]
# text="college name"
# # full_ratio.append(data.apply(get_ratio,axis=1))
# # partial_ratio=data.apply(get_partial_ratio,axis=1)
# # token_sort_ratio=data.apply(get_token_sort,axis=1)
# token_set_ratio.append(data.apply(lambda t:get_token_set_ratio(t,text),axis=1))
# # trigram=data.apply(get_trigram_ratio,axis=1)
# token_set_ratio=list(token_set_ratio[0][1:])

# index=token_set_ratio.index(max(list(token_set_ratio)))
# index
# value=data.iloc[index]
# # print(value)
# responses[value['tags']]

In [14]:

def check(text):
    token_set_ratio=[]
    token_ratio=[]
#     token_set_ratio=token_set_ratio.append(data.apply(lambda t:get_token_set_ratio(t,text),axis=1))
    token_set_ratio.append(data.apply(lambda t:get_token_set_ratio(t,text),axis=1))
    token_ratio.append(data.apply(lambda t:get_ratio(t,text),axis=1))
    
#     token_set_ratio.append(data.apply(lambda t:get_token_set_ratio(t,text),axis=1))

    token_set_ratio=list(token_set_ratio[0][1:])
    token_ratio=list(token_ratio[0][1:])
    print(max(list(token_set_ratio)))
    print(max(list(token_ratio)))
    if max(list(token_set_ratio))>90 and max(list(token_ratio))>=62:
        index=token_set_ratio.index(max(list(token_set_ratio)))
        value=data.iloc[index]
        responses[value['tags']]
    else:
        print("Try again")
        ask()
        
    return responses[value['tags']]

In [15]:
def chat(txt_pun):
    ntokens = word_tokenize(txt_pun)
    # stop_words = set(stopwords.words('english'))
    filter_sentence = [w for w in ntokens if not w.lower() in stop_words]
    filter_sentence = []
    for w in ntokens:
        if w not in stop_words:
            filter_sentence.append(w)

#     print(ntokens, "\n")
#     print(filter_sentence, "\n")
    punc = string.punctuation
            # print(punc)
    txt_pun = str(" ".join([c for c in filter_sentence if c not in string.punctuation]))
#     print(txt_pun)
    ans=check(txt_pun)
    print(ans)
#     talk(ans)
    #         record=mycol.find({"pattern": txt_pun})
    #         print(record)

In [16]:
def ask():
    while True:
        input_data = input("You- ")
        if input_data=="stop":
            print("Thank you")
        text = chat(input_data)
        text

In [ ]:
ask()

You- college nae
96
77
["SNJB's Late Sau. Kantabai Bhavarlalji Jain College of Engineering,Chandwad"]
You- placement information 2021 and 2022
100
100
['We have an excellent, attractive and pleasant ambiance library in the college. Library is located at first floor & Second floor of college building, having total area of 490 sq. mtr.']
You- stop
Thank you
21
26
Try again

In [24]:
algorithims.trigram("college name", "about name college")

0.684211

In [27]:
algorithims.cosine("information college", " about college name")

0.40824829046386296

In [8]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# Define the questions and answers
questions = [
    "What is TF-IDF vectorization?",
    "What is the purpose of TF-IDF?",
    "How does TF-IDF work?"
]

answers = [
    "TF-IDF (Term Frequency-Inverse Document Frequency) is a numerical representation of the importance of a word in a document. It is calculated as the product of term frequency and inverse document frequency.",
    "The purpose of TF-IDF is to assign a weight to each word in a document to reflect its importance in the document and in the corpus (collection of documents) as a whole.",
    "TF-IDF works by first calculating the term frequency of each word in a document. This represents how frequently the word appears in the document. The inverse document frequency is then calculated as the logarithm of the total number of documents divided by the number of documents containing the word. The final TF-IDF weight is obtained by multiplying the term frequency and inverse document frequency."
]

# Create a TfidfVectorizer object
vectorizer = TfidfVectorizer()
# Fit the vectorizer to the questions
X = vectorizer.fit_transform(questions)
# print(X)
# Define a function to get the most similar question to a given input
def get_answer(input_question):
    input_vector = vectorizer.transform([input_question])
#     print(input_vector)
    cosine_similarities = np.dot(input_vector, X.T).toarray()[0]
    print(cosine_similarities)
    most_similar_index = cosine_similarities.argmax()
    print(most_similar_index)
    return answers[most_similar_index]



# Test the chatbot
input_question = "What does TF-IDF measure?"
print(get_answer(input_question))

[0.50062937 0.38389075 0.5851873 ]
2
TF-IDF works by first calculating the term frequency of each word in a document. This represents how frequently the word appears in the document. The inverse document frequency is then calculated as the logarithm of the total number of documents divided by the number of documents containing the word. The final TF-IDF weight is obtained by multiplying the term frequency and inverse document frequency.